#!/usr/bin/env python
import logging
import os
import sys 
import urllib
import urllib2
try:
    import json
except ImportError:
    import simplejson as json

LOG = logging.getLogger(__name__)

REQUEST_HEADERS = {
    "Content-Type": "application/x-www-form-urlencoded",
    "Accept": "text/plain"}

def sxemail(url, user, passwd, subject, message):
    if not LOG.isEnabledFor(logging.DEBUG):
        LOG.info('Email, subject: %s, message: %.200s ...', subject, message)

    ent = {
        'template': 'monitor_diagnostics',
        'organizationId': 0,
        'emailRecipient': 'TO_ALTERNATE_EMAIL',
        'alternateEmailAddress': 'diagnostics@scalextreme.com',
        'subject': subject,
        'message': message
    }
    data = urllib.urlencode({
        'username': user,
        'password': passwd,
        'ent': json.dumps(ent)
    })

    LOG.debug('Request, url: %s, data: %s', url, data)

    request = urllib2.Request(url, data, REQUEST_HEADERS)
    response = urllib2.urlopen(request)

    if LOG.isEnabledFor(logging.DEBUG):
        LOG.debug('Response, code: %s, data: %s',
                response.getcode(), response.read())

if __name__ == '__main__':
    log_dir = os.environ.get('LOG_DIR', '/var/log')
    log_file = os.path.join(log_dir, 'sxemail.log')
    log_level = os.environ.get('ACTION_LOG_LEVEL', 'INFO').upper()
    logging.basicConfig(filename=log_file, level=logging.getLevelName(log_level),
            format='%(levelname)s - %(asctime)s - %(name)s - %(message)s')

    sx_email_url = os.environ.get('SX_EMAIL_URL', 'SX_EMAIL_URL_ENV_MISSING')
    sx_user = os.environ.get('SX_USER', 'SX_USER_ENV_MISSING')
    sx_pass = os.environ.get('SX_PASS', 'SX_PASS_ENV_MISSING')
    subject = sys.argv[2]
    message = sys.argv[3]
    
    sxemail(sx_email_url, sx_user, sx_pass, subject, message)
