#!/usr/bin/env python
import logging
import os
import sys 
import httplib, urllib
try:
    import json
except ImportError:
    import simplejson as json


def sxemail(store_host, store_user, store_pass, subject, message):
    ent = {
        'template': 'monitor_diagnostics',
        'organizationId': 0,
        'emailRecipient': 'TO_ALTERNATE_EMAIL',
        'alternateEmailAddress': 'diagnostics@scalextreme.com',
        'subject': subject,
        'message': message
    }
    params = urllib.urlencode({
        'username': store_user,
        'password': store_pass,
        'ent': json.dumps(ent)
    })
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "text/plain"}
    url_path = "/actmgnt/emailnotifier"

    logging.debug('Request POST, url: https://%s%s, headers: %s, body: %s',
            store_host, url_path, headers, params)

    conn = httplib.HTTPSConnection(store_host)
    conn.request("POST", url_path, params, headers)
    response = conn.getresponse()
    body = response.read()
    logging.debug('Response, code: %s %s, headers: %s, body: %s',
           response.status, response.reason, response.getheaders(), body)

if __name__ == '__main__':
    log_dir = os.environ.get('LOG_DIR', '/var/log')
    log_file = log_dir + '/sxemail.log'
    logging.basicConfig(filename=log_file, level=logging.DEBUG,
            format='%(levelname)s - %(asctime)s - %(name)s - %(message)s')

    logging.info('Email script called, cmd line args: %s', sys.argv)

    store_host = os.environ.get('STOREIP', 'STOREIP_ENV_MISSING')
    store_user = os.environ.get('STOREUSER', 'STOREUSER_ENV_MISSING')
    store_pass = os.environ.get('STOREPASS', 'STOREPASS_ENV_MISSING')
    subject = sys.argv[2]
    message = sys.argv[3]
    
    sxemail(store_host, store_user, store_pass, subject, message)
